### ISSUE TITLE
Exporting font does not work for sources not yet saved at least once

### ISSUE THREAD

**Issue by florianpircher** [googlefonts/fontc-export-plugin#2]
Continuing from https://github.com/schriftgestalt/glyphs-packages/pull/146

I am not sure what the root cause is, but when I create a new empty document, export fails. Once once I save the document to a file does the export works:

https://github.com/googlefonts/fontc-export-plugin/assets/3776198/caaf2e5c-827a-4e6e-b973-f3a1fa9dbbcb

**Comment by anthrotype** [comment]
thanks, I was able to reproduce now. I looks like when the GSFont is saved from python code (with .save() method like the plugin is doing), it does not set the `.appVersion` string for some reason; only when doing "Save" from the File menu (or CMD-S), it gets set:

```diff
$ diff -u /Users/clupo/Downloads/New\ Font\ 2.glyphs /Users/clupo/Downloads/New\ Font\ 2\ \(unsaved\).glyphs
--- /Users/clupo/Downloads/New Font 2.glyphs	2024-05-16 13:55:54
+++ /Users/clupo/Downloads/New Font 2 (unsaved).glyphs	2024-05-16 13:55:13
@@ -1,5 +1,5 @@
 {
-.appVersion = "3306";
+.appVersion = "";
 .formatVersion = 3;
 date = "2024-05-16 12:55:06 +0000";
 familyName = "New Font";
```

We should probably relax the strictness of fontc parser for the ".appVersion" field and allow empty string.
I wonder why there's such a difference though between saving from code or from UI.

**Comment by schriftgestalt** [comment]
An empty appVersion string is invalid.
I fixed it in Glyphs.

**Comment by anthrotype** [comment]
thank you!

**Comment by florianpircher** [comment]
Thanks for looking into this and thanks for pointing out the relocatable Python installation!
